<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SGECAR.Business</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGECAR.Data\SGECAR.Data.csproj" />
    <ProjectReference Include="..\SGECAR.Shared\SGECAR.Shared.csproj" />
  </ItemGroup>

</Project>
